package com.testmyaptitude.pojo;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Quant generated by hbm2java
 */
@Entity
@Table(name = "quant", catalog = "luq7bmtf_spatil")
public class Quant implements java.io.Serializable {

	private Integer qid;
	private String direction;
	private String passage;
	private String question;
	private String option_1;
	private String option_2;
	private String option_3;
	private String option_4;
	private String option_5;
	private Integer answer;

	public Quant() {
	}

	public Quant(String direction, String passage, String question, String option1, String option2, String option3,
			String option4, String option5, Integer answer) {
		this.direction = direction;
		this.passage = passage;
		this.question = question;
		this.option_1 = option1;
		this.option_2 = option2;
		this.option_3 = option3;
		this.option_4 = option4;
		this.option_5 = option5;
		this.answer = answer;
	}
	@Override
	public String toString() {
		return "question [qid=" + qid + ", direction=" + direction + ", passage=" + passage + ", question=" + question
				+ ", option_1=" + option_1 + ", option_2=" + option_2 + ", option_3=" + option_3 + ", option_4=" + option_4
				+ ", option_5=" + option_5 + ", answer=" + answer + "]";
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "QID", unique = true, nullable = false)
	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	@Column(name = "DIRECTION", length = 256)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "PASSAGE", length = 500)
	public String getPassage() {
		return this.passage;
	}

	public void setPassage(String passage) {
		this.passage = passage;
	}

	@Column(name = "QUESTION", length = 500)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "OPTION_1", length = 100)
	public String getOption1() {
		return this.option_1;
	}

	public void setOption1(String option1) {
		this.option_1 = option1;
	}

	@Column(name = "OPTION_2", length = 100)
	public String getOption2() {
		return this.option_2;
	}

	public void setOption2(String option2) {
		this.option_2 = option2;
	}

	@Column(name = "OPTION_3", length = 100)
	public String getOption3() {
		return this.option_3;
	}

	public void setOption3(String option3) {
		this.option_3 = option3;
	}

	@Column(name = "OPTION_4", length = 100)
	public String getOption4() {
		return this.option_4;
	}

	public void setOption4(String option4) {
		this.option_4 = option4;
	}

	@Column(name = "OPTION_5", length = 100)
	public String getOption5() {
		return this.option_5;
	}

	public void setOption5(String option5) {
		this.option_5 = option5;
	}

	@Column(name = "ANSWER")
	public Integer getAnswer() {
		return this.answer;
	}

	public void setAnswer(Integer answer) {
		this.answer = answer;
	}

}
