package com.testmyaptitude.pojo;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.ColumnDefault;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "luq7bmtf_spatil", uniqueConstraints = @UniqueConstraint(columnNames = "EMAIL"))
public class Users implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "EMAIL", unique = true, length = 30)
	private String email;
	
	@Column(name = "PASSWORD", length = 20)
	private String password;
	
	@Column(name = "FNAME", length = 15)
	private String fname;
	
	@Column(name = "LNAME", length = 15)
	private String lname;
	
	@Column(name = "GENDER", length = 6)
	private String gender;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 10)
	private Date dob;

	@Column(name = "MOBILENO", length = 15)
	private String mobileno;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Entry_Time")
	private Date entryTime;
	public Date getEntryTime() {
		return entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public Users() {
	}

	public Users(String email, String password, String fname, String lname, String gender, Date dob, String mobileno) {
		this.email = email;
		this.password = password;
		this.fname = fname;
		this.lname = lname;
		this.gender = gender;
		this.dob = dob;
		this.mobileno = mobileno;
	}
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

}
